feature: add yaml set Package
elliotchance/dingo pull request #17
Opened 2021-02-19 06:56 UTC by cq-z

2021-02-19 20:47 UTC, elliotchance requested changes
This change is fine, but can you also make a note of this in the README as well. Perhaps as a note under Building the Container.

2021-02-20 01:47 UTC, cq-z commented
@elliotchance it is ok?

2021-02-20 20:02 UTC, elliotchance approved these changes

2021-02-20 20:03 UTC, merged

2021-02-20 20:04 UTC, elliotchance commented
Yes, that's perfect: https://github.com/elliotchance/dingo/releases/tag/v1.4.0